In [2]:
import numpy as np

In [3]:
a  = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(np.full(3,5))


[5 5 5]


In [8]:
print(np.eye(5,4,k=0,dtype='int'))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [9]:
print(np.eye(5,4,k=1,dtype='int'))

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
print(np.eye(5,4,k=-1,dtype='int'))

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [12]:
print(np.random.random((5,2)))

[[0.06233307 0.81744151]
 [0.11162811 0.26888255]
 [0.13392068 0.20732023]
 [0.73942643 0.45578372]
 [0.42810852 0.44764236]]


# 1D indexing

In [1]:
import numpy as np

a = np.array([10,20,30,40,50])

# basic
print(a[0])     # 10  ← first
print(a[-1])    # 50  ← last
print(a[1:4])   # [20 30 40] ← slice
print(a[::2])   # [10 30 50] ← step

# fancy indexing
print(a[[0,2,4]])  # [10 30 50] ← specific indexes!

10
50
[20 30 40]
[10 30 50]
[10 30 50]


# 2D indexing

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(a[0])       # [1 2 3]    ← row 0
print(a[0,0])     # 1          ← row 0 col 0
print(a[1,2])     # 6          ← row 1 col 2
print(a[:,1])     # [2 5 8]    ← all rows col 1
print(a[0,:])     # [1 2 3]    ← row 0 all cols
print(a[0:2,0:2]) # [[1 2]     ← subarray
                  #  [4 5]]
print(a[-1,-1])   # 9          ← last element!

# fancy indexing 2D
print(a[[0,2]])   # rows 0 and 2
# [[1 2 3]
#  [7 8 9]]

# Sort

In [2]:
a = np.array([3,1,4,1,5,9,2,6])

# sort ascending
print(np.sort(a))         # [1 1 2 3 4 5 6 9] ✅
print(a)                  # [3 1 4 1 5 9 2 6] ← original unchanged!

# sort descending
print(np.sort(a)[::-1])   # [9 6 5 4 3 2 1 1]

# argsort → returns indexes of sorted order
print(np.argsort(a))      # [1 3 6 0 2 4 7 5]
#                            ↑ index of smallest

# sort in place
a.sort()                  # modifies original!
print(a)                  # [1 1 2 3 4 5 6 9]

# sort 2D array
b = np.array([[3,1,2],
              [6,4,5]])

print(np.sort(b, axis=0))  # sort each column
# [[3 1 2]
#  [6 4 5]]

print(np.sort(b, axis=1))  # sort each row
# [[1 2 3]
#  [4 5 6]]

[1 1 2 3 4 5 6 9]
[3 1 4 1 5 9 2 6]
[9 6 5 4 3 2 1 1]
[1 3 6 0 2 4 7 5]
[1 1 2 3 4 5 6 9]
[[3 1 2]
 [6 4 5]]
[[1 2 3]
 [4 5 6]]


# Unique

In [3]:
a = np.array([1,2,2,3,3,3,4,4,4,4])

# unique values
print(np.unique(a))
# [1 2 3 4]

# unique with counts
values, counts = np.unique(a, return_counts=True)
print(values)   # [1 2 3 4]
print(counts)   # [1 2 3 4] ← how many times each!

# unique with indexes
values, idx = np.unique(a, return_index=True)
print(values)   # [1 2 3 4]
print(idx)      # [0 1 3 6] ← first occurrence index

# unique 2D
b = np.array([[1,2,3],
              [1,2,4]])
print(np.unique(b))   # [1 2 3 4] ← flattened!

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[0 1 3 6]
[1 2 3 4]


# WHERE

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

# where condition → returns indexes
print(np.where(a > 5))
# (array([5, 6, 7, 8, 9]),)  ← indexes where condition true!

# where with values → replace!
print(np.where(a > 5, a, 0))
# [0 0 0 0 0 6 7 8 9 10]
# ↑ 0 where false, keep value where true!

print(np.where(a % 2 == 0, "even", "odd"))
# ['odd' 'even' 'odd' 'even'...]

# practical example
marks = np.array([85, 45, 92, 38, 78, 55])
result = np.where(marks >= 40, "Pass", "Fail")
print(result)
# ['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']

# nested where
grade = np.where(marks>=90, "A",
        np.where(marks>=80, "B",
        np.where(marks>=70, "C",
        np.where(marks>=40, "D", "F"))))
print(grade)
# ['B' 'D' 'A' 'F' 'C' 'D']

(array([5, 6, 7, 8, 9], dtype=int64),)
[ 0  0  0  0  0  6  7  8  9 10]
['odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even']
['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']
['B' 'D' 'A' 'F' 'C' 'D']


# APPEND

In [6]:
a = np.array([1,2,3,4,5])

# append single value
print(np.append(a, 6))
# [1 2 3 4 5 6]

# append multiple values
print(np.append(a, [6,7,8]))
# [1 2 3 4 5 6 7 8]

# append to 2D — flattens by default!
b = np.array([[1,2,3],
              [4,5,6]])

print(np.append(b, [[7,8,9]], axis=0))  # add row
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

print(np.append(b, [[7],[8]], axis=1))  # add column
# [[1 2 3 7]
#  [4 5 6 8]]

# NOTE: append returns new array!
a = np.append(a, 6)   
print(a)   # [1 2 3 4 5 6]

[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 7]
 [4 5 6 8]]
[1 2 3 4 5 6]


# Filter

In [7]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

# filter even numbers
print(a[a % 2 == 0])     # [2 4 6 8 10]

# filter greater than 5
print(a[a > 5])           # [6 7 8 9 10]

# filter multiple conditions
print(a[(a > 3) & (a < 8)])   # [4 5 6 7]
print(a[(a < 3) | (a > 8)])   # [1 2 9 10]

# filter with boolean array
mask = np.array([True,False,True,False,True,False,True,False,True,False])
print(a[mask])            # [1 3 5 7 9]

# practical example
students = np.array([85,45,92,38,78,55,67,91])
passed   = students[students >= 40]
print(passed)   # [85 45 92 78 55 67 91]

failed = students[students < 40]
print(failed)   # [38]

# filter 2D
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(b[b > 5])   # [6 7 8 9] ← flattened!

[ 2  4  6  8 10]
[ 6  7  8  9 10]
[4 5 6 7]
[ 1  2  9 10]
[1 3 5 7 9]
[85 45 92 78 55 67 91]
[38]
[6 7 8 9]


# all in example

In [8]:
import numpy as np

# student marks
marks = np.array([85,45,92,38,78,55,67,91,72,88])

print("All marks    :", marks)
print("Sorted       :", np.sort(marks))
print("Unique       :", np.unique(marks))
print("Passed       :", marks[marks >= 40])
print("Failed       :", marks[marks < 40])
print("Top 3 indexes:", np.argsort(marks)[-3:])
print("Grades       :", np.where(marks>=90,"A",
                        np.where(marks>=80,"B",
                        np.where(marks>=70,"C",
                        np.where(marks>=40,"D","F")))))

# add new mark
marks = np.append(marks, 95)
print("After append :", marks)

# where marks > 80
print("Indexes>80   :", np.where(marks > 80))

All marks    : [85 45 92 38 78 55 67 91 72 88]
Sorted       : [38 45 55 67 72 78 85 88 91 92]
Unique       : [38 45 55 67 72 78 85 88 91 92]
Passed       : [85 45 92 78 55 67 91 72 88]
Failed       : [38]
Top 3 indexes: [9 7 2]
Grades       : ['B' 'D' 'A' 'F' 'C' 'D' 'D' 'A' 'C' 'B']
After append : [85 45 92 38 78 55 67 91 72 88 95]
Indexes>80   : (array([ 0,  2,  7,  9, 10], dtype=int64),)
