In [2]:
import numpy as np

In [3]:
a  = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(np.full(3,5))


[5 5 5]


In [8]:
print(np.eye(5,4,k=0,dtype='int'))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [9]:
print(np.eye(5,4,k=1,dtype='int'))

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
print(np.eye(5,4,k=-1,dtype='int'))

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [12]:
print(np.random.random((5,2)))

[[0.06233307 0.81744151]
 [0.11162811 0.26888255]
 [0.13392068 0.20732023]
 [0.73942643 0.45578372]
 [0.42810852 0.44764236]]
