In [79]:
import numpy as np

# 5

In [80]:
arr = np.arange(1,41).reshape(4,10)
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [81]:
print(arr[:3,:4])

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]


In [82]:
print(arr[:2,4:5])

[[ 5]
 [15]]


In [83]:
print(arr[2:4])

[[21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [84]:
print(arr[:,(3,4,5)])

[[ 4  5  6]
 [14 15 16]
 [24 25 26]
 [34 35 36]]


# 8

In [85]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [86]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

# 9

In [87]:
arr = np.where(arr%2==0,-1,arr)
print(arr)

[ 1 -1  3 -1  5 -1  7 -1  9 -1]


In [88]:
arr1 = np.arange(1,11)

arr1[arr1%2==0] = -1

In [89]:
arr1

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9, -1])

# 10

In [90]:
arr1 = np.arange(1,6)
print(arr1)
arr2 = np.arange(6,11)
print(arr2)

print(np.append(arr1, arr2))
print(arr1)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]


In [91]:
print(np.append(arr1, arr2))

[ 1  2  3  4  5  6  7  8  9 10]


In [92]:
print(arr1)

[1 2 3 4 5]


# 11

In [93]:
arr = np.arange(1,17).reshape(2,8)
print(arr)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


# 12

In [94]:
arr = np.random.randint(13,41,12)
print(arr)

[14 14 18 31 14 39 13 13 35 13 16 18]


In [95]:
print(np.sort(arr))

[13 13 13 14 14 14 16 18 18 31 35 39]


In [96]:
print(np.sort(arr)[::-1])

[39 35 31 18 18 16 14 14 14 13 13 13]


In [97]:
arr = np.random.randint(13, 40, size=(3,4))
print(arr)

[[18 18 28 32]
 [15 15 39 14]
 [26 28 35 37]]


In [98]:
print(np.sort(arr,axis=0))

[[15 15 28 14]
 [18 18 35 32]
 [26 28 39 37]]


In [99]:
print(np.sort(arr,axis=1))

[[18 18 28 32]
 [14 15 15 39]
 [26 28 35 37]]


In [100]:
print(np.sort(arr)[::-1])

[[26 28 35 37]
 [14 15 15 39]
 [18 18 28 32]]


In [101]:
print(np.sort(arr,axis=None))

[14 15 15 18 18 26 28 28 32 35 37 39]


# 13

In [102]:
arr = np.random.randint(1,17,16)
print(arr)
def isPrime(n):
    if n < 2:
        return 0
    for i in range(2, n+1):
        if n % i == 0:
            return False
    return False

arr = [x for x in arr if isPrime(x)]
print(arr)

[16  1 16  7  5  6 14  3  3 14 12  1 12  4 10 12]
[]


In [103]:
def isPrime(n):
    if n < 2:
        return 0
    for i in range(2, n+1):
        if n % i == 0:
            return False
    return True

In [104]:
arr = [x for x in arr if isPrime(x)]
print(arr)

[]


In [105]:
arr = np.random.randint(1,17,16)
print(arr)

def isPrime(n):
    if n < 2:
        return False          
    for i in range(2, int(n**0.5)+1):  
        if n % i == 0:
            return False      
    return True               

p = [x for x in arr if isPrime(x)]
print(p)

[ 5  2 12 10 14 10  7 10 13  7 14 13  1  5 15 13]
[5, 2, 7, 13, 7, 13, 5, 13]


In [106]:
print(type(p))

<class 'list'>
