In [111]:
import numpy as np

# 5

In [112]:
arr = np.arange(1,41).reshape(4,10)
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [113]:
print(arr[:3,:4])

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]


In [114]:
print(arr[:2,4:5])

[[ 5]
 [15]]


In [115]:
print(arr[2:4])

[[21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [116]:
print(arr[:,(3,4,5)])

[[ 4  5  6]
 [14 15 16]
 [24 25 26]
 [34 35 36]]


# 8

In [117]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [118]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

# 9

In [119]:
arr = np.where(arr%2==0,-1,arr)
print(arr)

[ 1 -1  3 -1  5 -1  7 -1  9 -1]


In [120]:
arr1 = np.arange(1,11)

arr1[arr1%2==0] = -1

In [121]:
arr1

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9, -1])

# 10

In [122]:
arr1 = np.arange(1,6)
print(arr1)
arr2 = np.arange(6,11)
print(arr2)

print(np.append(arr1, arr2))
print(arr1)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]


In [123]:
print(np.append(arr1, arr2))

[ 1  2  3  4  5  6  7  8  9 10]


In [124]:
print(arr1)

[1 2 3 4 5]


# 11

In [125]:
arr = np.arange(1,17).reshape(2,8)
print(arr)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


# 12

In [126]:
arr = np.random.randint(13,41,12)
print(arr)

[20 27 20 34 24 20 18 21 14 17 40 21]


In [127]:
print(np.sort(arr))

[14 17 18 20 20 20 21 21 24 27 34 40]


In [128]:
print(np.sort(arr)[::-1])

[40 34 27 24 21 21 20 20 20 18 17 14]


In [129]:
arr = np.random.randint(13, 40, size=(3,4))
print(arr)

[[39 30 35 36]
 [29 24 19 39]
 [35 17 36 17]]


In [130]:
print(np.sort(arr,axis=0))

[[29 17 19 17]
 [35 24 35 36]
 [39 30 36 39]]


In [131]:
print(np.sort(arr,axis=1))

[[30 35 36 39]
 [19 24 29 39]
 [17 17 35 36]]


In [132]:
print(np.sort(arr)[::-1])

[[17 17 35 36]
 [19 24 29 39]
 [30 35 36 39]]


In [133]:
print(np.sort(arr,axis=None))

[17 17 19 24 29 30 35 35 36 36 39 39]


# 13

In [134]:
arr = np.random.randint(1,17,16)
print(arr)
def isPrime(n):
    if n < 2:
        return 0
    for i in range(2, n+1):
        if n % i == 0:
            return False
    return False

arr = [x for x in arr if isPrime(x)]
print(arr)

[11  9  8  2  6 16 11 14 15  5 11  2 13 10  6  6]
[]


In [135]:
def isPrime(n):
    if n < 2:
        return 0
    for i in range(2, n+1):
        if n % i == 0:
            return False
    return True

In [136]:
arr = [x for x in arr if isPrime(x)]
print(arr)

[]


In [137]:
arr = np.random.randint(1,17,16)
print(arr)

def isPrime(n):
    if n < 2:
        return False          
    for i in range(2, int(n**0.5)+1):  
        if n % i == 0:
            return False      
    return True               

p = [x for x in arr if isPrime(x)]
print(p)

[ 3  6  9 10  4  6 12  9 15 10 12 13 13 12  3  9]
[3, 13, 13, 3]


In [138]:
print(list(filter(isPrime,arr)))

[3, 13, 13, 3]


In [139]:
print(type(p))

<class 'list'>
